<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.0.0.379
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Innsending av approach Form',
	'heading' => 'Ny innsending av skjema',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Avmerket',
		'checkbox_unchecked' => 'Ikke avmerket',
		'submitted_from' => 'Skjema sendt fra webområde: %s',
		'submitted_by' => 'IP-adresse for besøkende: %s',
		'too_many_submissions' => 'For mange nylige innsendinger fra denne IP-adressen',
		'failed_to_send_email' => 'Kan ikke sende e-post',
		'invalid_reCAPTCHA_private_key' => 'Ugyldig reCAPTCHA-privatnøkkel.',
		'invalid_reCAPTCHA2_private_key' => 'Ugyldig reCAPTCHA 2.0-privatnøkkel.',
		'invalid_reCAPTCHA2_server_response' => 'Ugyldig reCAPTCHA 2.0-serverrespons.',
		'invalid_field_type' => 'Ukjent felttype, %s.',
		'invalid_form_config' => 'Feltet %s har en ugyldig konfigurasjon.',
		'unknown_method' => 'Ukjent serverforespørselsmetode'
	),
	'email' => array(
		'from' => 'jonascarlsen1992@gmail.com',
		'to' => 'jonascarlsen1992@gmail.com'
	),
	'fields' => array(
		'custom_U8609' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Custom:',
			'required' => true,
			'errors' => array(
				'required' => 'Feltet Custom: er obligatorisk.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Custom:',
			'required' => true,
			'errors' => array(
				'required' => 'Feltet Custom: er obligatorisk.',
				'format' => 'Feltet Custom: inneholder en ugyldig e-postadresse.'
			)
		),
		'custom_U8613' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Custom:',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U8619' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Custom:',
			'required' => true,
			'errors' => array(
				'required' => 'Feltet Custom: er obligatorisk.'
			)
		)
	)
);

process_form($form);
?>
